// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportBundle():Promise<void>;

export function SendPrompt():Promise<void>;

export function StartSession(arg1:string):Promise<void>;

export function StopSession():Promise<void>;
