// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportBundle() {
  return window['go']['app']['App']['ExportBundle']();
}

export function SendPrompt() {
  return window['go']['app']['App']['SendPrompt']();
}

export function StartSession(arg1) {
  return window['go']['app']['App']['StartSession'](arg1);
}

export function StopSession() {
  return window['go']['app']['App']['StopSession']();
}
